language: cpp
compiler:
  - gcc

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install swig python-dev cmake
    - SOURCE_DIR=`pwd`
    - rm -fr /tmp/cmake-build/third-party/ 
    - cd /tmp
    - wget https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.gz -O boost_1_63_0.tar.gz
    - tar xf boost_1_63_0.tar.gz
    - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz -O gtest-1.7.0.tar.gz
    - tar xf gtest-1.7.0.tar.gz
    - mkdir gtest.build && cd gtest.build
    - cmake /tmp/googletest-release-1.7.0  -DBUILD_SHARED_LIBS=ON
    - make
    - sudo cp -v /tmp/gtest.build/*.so /usr/local/lib
    - sudo cp -rv /tmp/googletest-release-1.7.0/include/gtest /usr/local/include/

script:
- cd $SOURCE_DIR/../ && mkdir libkml.build && cd libkml.build && export CMAKE_PREFIX_PATH=/tmp/boost_1_63_0
- cmake -DCMAKE_INSTALL_PREFIX=/tmp/local $SOURCE_DIR -DBUILD_TESTING=ON && make
- ctest
